### ISSUE TITLE
Missing toolchain documentation and missing generator features

### ISSUE THREAD

**Issue by cjsmeele** [R2D2-2017/R2D2-2017#18]
Just writing this down here as I don't have any more time today:

As noted by @timijntema, we need the following:
- instructions on adding files to CMakelists (everyone should know this by now, but for completion sake)
- instructions on adding libraries (NB: you must contact a lead for this, because build server must support it, among other reasons)

Also missing is:
- Instructions on setting up a Codelite workspace
bmptk++ supports this halfway currently, with a `--override-generator` flag, but this is not module specific currently (i.e. no `-m` flag)! Not good for those who only want codelite for arduino projects.
You'd probably use `CodeLite - Unix Makefiles` for the generator by the way. Haven't had a chance to test this myself. I'll see if I can pick this up tomorrow when @TheHippiez sets up his environment.

**Comment by sqrtroot** [comment]
Fixed the also missing part

**Comment by cjsmeele** [comment]
Closing - no longer relevant.
