### ISSUE TITLE
hwlib issues

### ISSUE THREAD

**Issue by cjsmeele** [R2D2-2017/R2D2-2017#5]
Two problems with the current hwlib setup:

- Pin numbers are incorrect somehow (cannot blink LED on d13) -> Can be fixed by pulling in https://github.com/wovo/hwlib/commit/3a50d189256681f453279ad5598bfd0abae3a2dc
- `hwlib::cout` is broken, as tested by both me and @kasumi-owari. Don't know if this is in hwlib or if something's burning on our side, but we get no output at all on the serial line.

**Comment by sqrtroot** [comment]
To fix `hwlib::cout` maybe try compiling with defining `HWCPP_FAKE_OSTREAM`

**Comment by sqrtroot** [comment]
For your reference these are all the flags found by running the following command on a hwlib+bmptk example from wovo:
```-c
-C
-DBMPTK_BAUDRATE=38400
-DBMPTK_CHIP=atsam3x8e
-DBMPTK_CHIP_atsam3x8e
-DBMPTK_EMBEDDED
-DBMPTK_INCLUDE_CHIP=sam.h
-DBMPTK_TARGET=arduino_due
-DBMPTK_TARGET_arduino_due
-DBMPTK_VERSION=V03_00_work_in_progress_2016_07_04
-DBMPTK_XTAL=12000
-DDONT_USE_CMSIS_INIT
-DHWCPP_FAKE_OSTREAM
-DRAM_SIZE=96k
-DRAM_START=0x20000000
-DROM_SIZE=512k
-DROM_START=0x00000000
-D__SAM3X8E__
-DSTACK_SIZE=81920
-E
-fdata-sections
-ffunction-sections
-fno-exceptions
-fno-rtti
-fno-threadsafe-statics
-fno-use-cxa-get-exception-ptr
-fomit-frame-pointer
-I../bmptk/
-I../bmptk//targets
-I../bmptk//targets/cortex
-I../bmptk//targets/cortex/atmel
-I../bmptk//targets/cortex/atmel/sam3xa/source/as_gcc
-I../bmptk//targets/cortex/cmsis
-I../hwlib
-I../rtos
-lgcc
-march=armv7-m
-mcpu=cortex-m3
-mthumb
-none-eabi-g++"
-none-eabi-gcc"
-none-eabi-objcopy"
-nostartfiles
-o
-O
-Os
-P
-R
-std=c11
-std=c++14
-T
--version
-Wall
-Werror
-with-cpp
-Wl,-fatal-warnings
-Wl,--gc-sections
-Wl,-Map,main.map
-Wno-maybe-uninitialized
-Wno-unused-local-typedefs
-x
```
Found with the command `make -n | grep -P "\-\S*" -o | tr " "\n"
" | sort | uniq`

**Comment by ManDeJan** [comment]
I also encountered this issue in my example [link](https://github.com/ManDeJan/kvasir-toolchain-hwlib-example) Looking through the ostream files in hwlib I think we need to define `HWLIB_ONCE` https://github.com/wovo/hwlib/blob/master/library/hwlib-ostream.hpp#L783-L788

**Comment by cjsmeele** [comment]
@ManDeJan We already have a `HWLIB_ONCE` in `wrap-hwlib.cc`.

**Comment by cjsmeele** [comment]
By copying most of the BMPTK macros I'm getting output, but it's corrupted:
```
add_definitions(-DBMPTK_TARGET_arduino_due                                                       
                -DBMPTK_TARGET=arduino_due
                -D__SAM3X8E__
                -DHWCPP_FAKE_OSTREAM
                -DBMPTK_CHIP=atsam3x8e
                -DBMPTK_CHIP_atsam3x8e
                -DBMPTK_XTAL=12000
                -DBMPTK_EMBEDDED
                -DBMPTK_BAUDRATE=38400)
```
(verified the baudrate in minicom, same issue in lpc21isp)
![a](https://cloud.githubusercontent.com/assets/2670982/26328076/ea117a34-3f41-11e7-895f-55dcda46c213.png)
