### ISSUE TITLE
Missing build env documentation for Windows

### ISSUE THREAD

**Issue by cjsmeele** [R2D2-2017/R2D2-2017#6]
Just quickly writing this down here, needs to be added to the wiki soon:
the device location from kvasir-toolchain is set to ttyACM0 by default. Windows users need to run the cmake utility to set it to COMn where their due is plugged in.
Additionally, instructions need to be written for opening a serial terminal (e.g. `lpc21isp` á la wovo, or putty).

**Comment by ManDeJan** [comment]
The COM setttings is fixed by https://github.com/R2D2-2017/R2D2-2017/commit/8ff2d31f78b00a2b409dad61efe75e91ed97cd0e, currently working on the terminal instructions

**Comment by ManDeJan** [comment]
Terminal instructions are now on the wiki
https://github.com/R2D2-2017/R2D2-2017/wiki/Development-Workflow
