### ISSUE TITLE
No device found on ttyACM0 - arduino connected

### ISSUE THREAD

**Issue by Bob-Thomas** [R2D2-2017/R2D2-2017#9]
After checking out from development and creating my module I tried to flash a simple blink thing.
```
#include <sam3x8e.h>
#include "wrap-hwlib.hh"
int main() {
    WDT->WDT_MR = WDT_MR_WDDIS;

    auto pin = hwlib::target::pin_out(hwlib::target::pins::d13);

    while(true) {
        hwlib::wait_ms(200);        
        pin.set(1);
        hwlib::wait_ms(200);
        pin.set(0);
    }
    return 0;
}
```
My arduino is connected on ttyACM0 and during the `make flash` it blinks showing it's connected.
But after a couple of seconds I get the message `No device found ttyACM0`.
So after some googling and checkout out my old arduino hwlib + bmptk project I noticed that I used to set my speed of ttyACM0 to 1200 with `sudo stty -F /dev/ttyACM0 speed 1200 cs8 -cstopb -parenb` .
After doing this I was able to flash my arduino with my blink example

Is this something that you guys also experienced?

**Comment by cloche-leythal-pastalia** [comment]
A pull request for the toolchain to fix this issue is ready at [run stty when flashing arduino due](https://github.com/sqrtroot/toolchain/pull/1) just waiting for it to get approved and merged now.

**Comment by sqrtroot** [comment]
Upstream toolchain is merged, but only for linux users,
Windows users still need to press the erase button so the due will startup it's flash loading program
